# Generated by Django 2.2.2 on 2019-06-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190629_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='1', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
