# Generated by Django 2.2.2 on 2019-06-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
