# Generated by Django 2.2.2 on 2019-06-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190629_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bathromms',
            new_name='bathrooms',
        ),
    ]
