# Generated by Django 2.2.2 on 2019-07-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquries', '0002_auto_20190701_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
