# Generated by Django 2.2.2 on 2019-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquries', '0003_auto_20190701_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
